-- Basic settings
require('legazim.options')
require('legazim.plugins')
require('legazim.keybinds')
require('legazim.colorscheme')
require('legazim.autocmd')
-- Code completion and LSP
require('legazim.cmp')
require('legazim.lsp')
-- Plugins configuration
require('legazim.config.autopairs')
require('legazim.config.bufferline')
require('legazim.config.colorizer')
require('legazim.config.gitsigns')
require('legazim.config.hop')
require('legazim.config.indent-blankline')
require('legazim.config.lualine')
require('legazim.config.mini')
require('legazim.config.nvimtree')
require('legazim.config.scrollbar')
require('legazim.config.telescope')
require('legazim.config.toggleterm')
require('legazim.config.treesitter')
require('legazim.config.trouble')
require('legazim.config.whichkey')
