-- Basic settings
require('legazim.options')
require('legazim.plugins')
require('legazim.keybinds')
require('legazim.colorscheme')
-- Plugins configuration
require('legazim.config.cmp')
require('legazim.config.trim')
require('legazim.config.lualine')
require('legazim.config.mini')
require('legazim.config.nvimtree')
require('legazim.config.telescope')
require('legazim.config.toggleterm')
require('legazim.config.scrollbar')
require('legazim.lsp')
